### ISSUE TITLE
Problem in abs_templates_ec/analog_mos/edge.py line 343:

### ISSUE THREAD

**Issue by mkosunen** [ucb-art/BAG2_TEMPLATES_EC#11]
The line 343 in  abs_templates_ec/analog_mos/edge.py commit   8cb110218e1e05 in its current form

```
out_info = tech_cls.get_outer_edge_info(guard_ring_nf, layout_info, is_end, outer_adj_blk,
                                                is_sub_ring=is_sub_ring)

```
returns an error
```
File "..../BAG2_TEMPLATES_EC/abs_templates_ec/analog_mos/edge.py", line 344, in draw_layout
    is_sub_ring=is_sub_ring)
TypeError: get_outer_edge_info() got an unexpected keyword argument 'is_sub_ring'

```
This seems to work: 
`out_info = tech_cls.get_outer_edge_info(guard_ring_nf, layout_info, is_end, outer_adj_blk)`

It seems to have gotten its current form in commit 6bd341f2 by @ayan-biswas . Cant say what is the correct/intented form.

I would have filed a pull request, but I can not push branches to this repo.

**Comment by ayan-biswas** [comment]
This is an extra feature added to BAG2_TEMPLATES_EC to support other processes, and tsmc16_FFC (which I assume you are using) has not been updated to use it.

Basically, as you have already figured out, tsmc16_FFC does not need this extra flag, but it is needed for other processes. You should not change this process agnostic generic implementation. The correct fix is to go to mos/base.py of the process (tsmc16_FFC in your case), and add an extra argument "**kwargs" to the process specific definition of the get_outer_edge_info() method. This allows the method to get multiple keyword arguments, as necessary.

Sorry for the delayed response - I was on vacation. Unfortunately I cannot do the above change since I do not have access to tsmc16, so you should raise this issue there.

Even if you are using some other process and face a similar issue, it is most probably a problem with the specific implementation and not the generic one, as I explained above.

**Comment by mkosunen** [comment]
In my process definition, I'm using
 "from abs_templates_ec.analog_mos.planar import MOSTechPlanarGeneric"

So in this case the method get_outer_edge_info is defined in
BAG2_TEMPLATES_EC/abs_templates_ec/analog_mos/planar.py as

def get_outer_edge_info(self, guard_ring_nf, layout_info, is_end, adj_blk_info)
 
So I think the **kwargs should be then added there, right?

**Comment by ayan-biswas** [comment]
I see, you are using planar technology. I have only been working with finfets so far, so it is expected that planar.py and soi.py are not updated.

What you suggested, sounds correct to me. Basically all the abstract method definitions should have the same arguments list.

Please contact Eric about getting collaborator access to this repo, so that you can submit pull requests. Then he will review those and merge to master.

Thank you for bringing up this issue.

**Comment by pkerichang** [comment]
Just confirming Ayan's comments are correct; the method signature in the planar.py needs to be updated.

**Comment by mkosunen** [comment]
@pkerichang , OK, got it. Can you give me collaborator status so I can make the fix an file a pull request?
